src/ElasticSearch/JsonDocument/CopyJson/CopyJsonRelatedLocation.php, src/ElasticSearch/Offer/ElasticSearchOfferQueryBuilder.php, tests/ElasticSearch/Event/EventJsonDocumentTransformerTest.php, tests/ElasticSearch/Event/data/indexed-with-multiple-location-ids.json, tests/ElasticSearch/Event/data/original-with-duplicated-location.json
- The `location.id` on event documents is now indexed as an array of ids when the location has known duplicates.
---
Ticket: https://jira.uitdatabank.be/browse/III-3046
---
This does not require a schema change because Elasticsearch has no `array` datatype. Every field can always be indexed as `0...n` values out of the box: https://www.elastic.co/guide/en/elasticsearch/reference/5.2/array.html
=> Index id property of duplicated event location as array of ids

app/Console/CreateLowerCaseStandardAnalyzerCommand.php, app/Console/MigrateElasticSearchCommand.php, bin/app.php, src/ElasticSearch/Operations/CreateLowerCaseStandardAnalyzer.php, src/ElasticSearch/Operations/SchemaVersions.php, src/ElasticSearch/Operations/json/analyzer_lowercase_standard.json, src/ElasticSearch/Operations/json/mapping_event.json, src/ElasticSearch/Operations/json/mapping_organizer.json, src/ElasticSearch/Operations/json/mapping_place.json
- Fixed unpredictable query behaviour on `name`, `description`, `address.{language}.addressLocality` and `address.{language}.streetAddress` fields
---
Do not merge until we have checked with Stan that this is not an issue because we will lose  correction of spelling mistakes.
=> [DNM] Use standard lowercase analyzer instead of language-specific analyzers

.travis.yml
I'm trying to set up Travis CI for this repository, but builds are failing because we already had an old travis.yml file with config to also build for PHP 5.6 and 7 which we no longer support in general.
=> Remove PHP 5.6 and 7 builds

app/Offer/OfferSearchControllerFactory.php
- Fixed `isDuplicate` URL parameter no longer working.
---
Ticket: https://jira.uitdatabank.be/browse/III-3204
=> III-3204 Register IsDuplicateOfferRequestParser

app/ElasticSearchProvider.php, app/Event/EventServiceProvider.php, app/EventBusProvider.php, app/Place/PlaceServiceProvider.php
- Fixed some documents not being indexed in bulk but instead file per file when migrating to a new index, because the indexation strategy was not a singleton.
- Fixed the event bus not being a singleton and being instantiated multiple times.
- Fixed events and places not being re-indexed when migrating to a new index. The necessary messages were dispatched on the internal event bus, but the projectors for indexing events and places were not subscribed correctly.
---
Noticed this while working on #67 and testing the new field mapping
=> Fix ElasticSearch migrate issues

app/Offer/OfferSearchControllerFactory.php, readme.md, src/ElasticSearch/Event/CopyJsonEvent.php, src/ElasticSearch/JsonDocument/CopyJson/Components/CopyRelatedProduction.php, src/ElasticSearch/Offer/ElasticSearchOfferQueryBuilder.php, src/ElasticSearch/Operations/SchemaVersions.php, src/ElasticSearch/Operations/json/mapping_event.json, src/Http/Offer/RequestParser/RelatedProductionRequestParser.php, src/Http/OfferSearchController.php, src/Http/OrganizerSearchController.php, src/Http/Parameters/AbstractSupportedParameters.php, src/Http/Parameters/OfferParameterWhiteList.php, src/Http/Parameters/OfferSupportedParameters.php, src/Http/Parameters/OrganizerSupportedParameters.php, src/Offer/OfferQueryBuilderInterface.php, tests/ElasticSearch/Event/EventJsonDocumentTransformerTest.php, tests/ElasticSearch/Event/data/indexed-with-production.json, tests/ElasticSearch/Event/data/original-with-production.json, tests/ElasticSearch/Offer/ElasticSearchOfferQueryBuilderTest.php, tests/Http/MockOfferQueryBuilder.php, tests/Http/OfferSearchControllerTest.php
- Added production id filter
---
Ticket: https://jira.uitdatabank.be/browse/III-3473
---
Todo:
=> III-3473 Production id filter

app/Error/ApiExceptionHandler.php
- Allow throwable type as parameter for api problem report creation
---
Ticket: https://jira.uitdatabank.be/browse/III-3386
=> III-3386 Allow throwable for API report creation

src/ElasticSearch/JsonDocument/Properties/NameTransformer.php, tests/ElasticSearch/JsonDocument/EventTransformerTest.php, tests/ElasticSearch/JsonDocument/data/event/indexed-with-untranslated-dummy-organizer.json, tests/ElasticSearch/JsonDocument/data/event/original-with-untranslated-dummy-organizer-name.json
- Added fallback for untranslated organizer names (again, after removing it before, until we do another full replay at some point)
---
Ticket: https://jira.uitdatabank.be/browse/III-3584
=> III-3584 Re-add fallback for untranslated organizer names

.github/workflows/ci.yml
- CI pipeline now uses composer v2
---
Ticket: https://jira.uitdatabank.be/browse/III-3778
=> Use composer v2 in CI pipeline

app/Offer/OfferSearchControllerFactory.php, src/Http/Offer/RequestParser/AvailabilityOfferRequestParser.php, src/Http/Offer/RequestParser/CalendarOfferRequestParser.php, src/Http/OfferSearchController.php, src/Http/Parameters/ArrayParameterBagAdapter.php, tests/Http/OfferSearchControllerTest.php
- Added a conversion of whitespace to `+` in values provided in date parameters like `availableFrom`, `availableTo`, `dateFrom` and `dateTo`. This makes manual testing a lot easier because now we don't have to convert those to `%2B` anymore when doing a manual test. There's also no use case for whitespaces in those date parameters anyway.
=> Convert spaces in URL parameters with dates to plus signs

src/ElasticSearch/ElasticSearchDocumentRepository.php
- Return correct string type from `getDocumentType`
---
Ticket: https://jira.uitdatabank.be/browse/III-3774
=> III-3774 Return string instead of object

src/ElasticSearch/AbstractElasticSearchQueryBuilder.php, src/ElasticSearch/ElasticSearchPagedResultSetFactory.php, src/ElasticSearch/ElasticSearchPagedResultSetFactoryInterface.php, src/ElasticSearch/Offer/ElasticSearchOfferSearchService.php, src/ElasticSearch/Organizer/ElasticSearchOrganizerSearchService.php, src/Http/OfferSearchController.php, src/Http/OrganizerSearchController.php, src/Http/PagedCollectionFactory.php, src/Limit.php, src/PagedResultSet.php, src/QueryBuilder.php, src/Start.php, tests/ElasticSearch/ElasticSearchPagedResultSetFactoryTest.php, tests/ElasticSearch/Offer/ElasticSearchOfferQueryBuilderTest.php, tests/ElasticSearch/Offer/ElasticSearchOfferSearchServiceTest.php, tests/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilderTest.php, tests/ElasticSearch/Organizer/ElasticSearchOrganizerSearchServiceTest.php, tests/Http/MockOfferQueryBuilder.php, tests/Http/MockOrganizerQueryBuilder.php, tests/Http/OfferSearchControllerTest.php, tests/Http/OrganizerSearchControllerTest.php, tests/Http/PagedCollectionFactoryTest.php, tests/PagedResultSetTest.php
- Added min and max value on `limit` parameter on `/offers/`, `/events/`, `/places/`, and `/organizers/`
- Added min and max value on `start` parameter on `/offers/`, `/events/`, `/places/`, and `/organizers/`
- Removed usages of `Natural` for start and limit parameters, and in `PagedResultSet` class
---
Ticket: https://jira.uitdatabank.be/browse/III-3840
I based the values on the ones documented here: https://documentatie.uitdatabank.be/content/search_api_3/latest/getting-started/pagination.html
limit=2000 was around the threshold that made PHP run out of memory in the past I think.
start=10000 is based on the max starting position supported by Elasticsearch
=> III-3840 Min and max values for start and limit

app/Error/SentryExceptionHandler.php, composer.json, composer.lock, src/Http/OfferSearchController.php, src/Http/OrganizerSearchController.php, tests/Http/OfferSearchControllerTest.php
- Update `cultuurnet/udb3-api-guard` to version 4
---
Ticket: https://jira.uitdatabank.be/browse/III-3851
Note: more pull requests will be created to fully finish the removal of `cultuurnet/valueobjects`
=> III-3851 Update cultuurnet/udb3-api-guard to v4

composer.json, composer.lock
- https://github.com/cultuurnet/calendar-summary-v3/releases/tag/v3.2
---
Ticket: https://jira.uitdatabank.be/browse/III-3872
=> Update cultuurnet/calendar-summary-v3 to latest version

composer.json, composer.lock
- Fixed broken `./bin/app.php` script when using `composer install --no-dev`
=> Make symfony/console a regular dependency and not just a dev dependency

app/Error/ApiExceptionHandler.php, app/Factory/ErrorHandlerFactory.php
- Error responses were always sent as 500 regardless of the status in the Api Problem
---
Ticket: https://jira.uitdatabank.be/browse/III-3816
=> III-3816 Send correct status code

src/ElasticSearch/JsonDocument/JsonLdPolyfillJsonTransformer.php, src/Http/ResultTransformerFactory.php, tests/ElasticSearch/JsonDocument/JsonLdPolyfillJsonTransformerTest.php
- Added polyfill transformer similar to the one in UDB3 to correct some malformed properties at run-time (since the JSON-LD is cached in SAPI3 to prevent tens/hundreds of HTTP requests to udb3 which incur too much of a performance hit)
---
Ticket: https://jira.uitdatabank.be/browse/III-3951
=> III-3951 jsonld polyfill transformer

src/ElasticSearch/JsonDocument/JsonLdPolyfillJsonTransformer.php, tests/ElasticSearch/JsonDocument/JsonLdPolyfillJsonTransformerTest.php
- Embedding an offer in the search API no longer exposes the internal `metadata` property
---
Ticket: https://jira.uitdatabank.be/browse/III-3972
=> Remove internal properties of embedded document through polyfill

src/ElasticSearch/Operations/SchemaVersions.php, src/ElasticSearch/Operations/json/mapping_event.json, src/ElasticSearch/Operations/json/mapping_organizer.json, src/ElasticSearch/Operations/json/mapping_place.json
- Some events with a very large JSON-LD representation did not get indexed properly
---
Ticket: https://jira.uitdatabank.be/browse/III-3934
=> III-3934 - Use index 'no' instead of 'not-analyzed' to bypass the 32kb limit

app/Console/ConsumeCommand.php, composer.json, composer.lock
- Avoid non-blocking `wait` statement to improve performance. The wait used to be called in non-blocking mode and with a timeout. But when the mode is set to non-blocking the timeout is discarded.
---
For all details see this [PR](https://github.com/cultuurnet/udb3-silex/pull/613) on udb3-silex
=> Avoid non-blocking wait statement to improve performance

src/ElasticSearch/Operations/SchemaVersions.php, src/ElasticSearch/Operations/json/mapping_event.json, src/ElasticSearch/Operations/json/mapping_organizer.json, src/ElasticSearch/Operations/json/mapping_place.json
- Set `enabled` for `originalEncodedJsonLd` to `false`
- Set `type` of `originalEncodedJsonLd` to `object` so it does not get parsed as some kind of string
---
Ticket: https://jira.uitdatabank.be/browse/III-3934
The documentation for `enabled` for Elasticsearch 5.3: https://discuss.elastic.co/t/why-elasticsearch-still-check-the-length-of-a-keyword-field-even-if-its-not-indexed/134604/5
In more recent documentation it is clarified that you can also set the type to `object` for string values if you set `enable` to `false`: https://www.elastic.co/guide/en/elasticsearch/reference/7.x/enabled.html
> Note that because Elasticsearch completely skips parsing the field contents, it is possible to add non-object data to a disabled field
I got this solution from this question which is exactly the …
=> III-3934 Replace "no" with false

src/ElasticSearch/JsonDocument/Properties/Url.php, src/ElasticSearch/JsonDocument/Properties/UrlTransformer.php, src/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilder.php, tests/ElasticSearch/JsonDocument/Properties/UrlTransformerTest.php, tests/ElasticSearch/JsonDocument/data/organizer/all_languages_indexed.json, tests/ElasticSearch/JsonDocument/data/organizer/indexed.json, tests/ElasticSearch/JsonDocument/data/organizer/indexed_with_translated_address.json, tests/ElasticSearch/JsonDocument/data/organizer/indexed_with_workflowstatus_deleted.json, tests/ElasticSearch/JsonDocument/data/organizer/missing_main_language_indexed.json, tests/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilderTest.php
- Organizer URLs are now normalized like in UDB3 before being indexed
---
Ticket: https://jira.uitdatabank.be/browse/III-4104
Notes:
- The approach results in slightly different normalized URLs than in in UDB3, trailing slashes are now only removed from the path, not from a query or fragment. I will make a PR to use the same approach instead of a regex there
=> III-4104 Normalize organizer urls before indexation

app/RoutingServiceProvider.php
- Fixed incorrect error message for invalid client id by correctly disabling the Guzzle exceptions
---
Ticket: https://jira.uitdatabank.be/browse/III-4048
=> III-4048 Fix Guzzle client config

web/.htaccess
- Removed `QSA` flag in rewrite rules. This would combine the original query string with the query string in our rewrite rule, and causes the query string parameters to be reordered. However there is no query string in our new URL, so there is nothing to combine it with and it just reorders the original query parameters.
---
Ticket: https://jira.uitdatabank.be/browse/III-4214
=> III-4214 Remove QSA flag

app/RoutingServiceProvider.php
- Added support for `GET /event` and `GET /place` (with and without trailing slash) as aliases for `GET /events` and `GET /places`, so the possible endpoints are consistent with EntryAPI3
---
Ticket: https://jira.uitdatabank.be/browse/III-4177
=> Add support for singular /event and /place

src/ElasticSearch/JsonDocument/Properties/CalendarTransformer.php, src/ElasticSearch/Operations/SchemaVersions.php, tests/ElasticSearch/JsonDocument/data/event/indexed-permanent.json, tests/ElasticSearch/JsonDocument/data/event/indexed-with-multiple-dates-without-date-range.json, tests/ElasticSearch/JsonDocument/data/place/indexed-duplicate.json, tests/ElasticSearch/JsonDocument/data/place/indexed-for-all-ages.json, tests/ElasticSearch/JsonDocument/data/place/indexed-modified.json, tests/ElasticSearch/JsonDocument/data/place/indexed-with-end-date-as-available-to.json, tests/ElasticSearch/JsonDocument/data/place/indexed-with-metadata.json, tests/ElasticSearch/JsonDocument/data/place/indexed-with-optional-fields.json, tests/ElasticSearch/JsonDocument/data/place/indexed-with-regions.json, tests/ElasticSearch/JsonDocument/data/place/indexed-without-available-from.json, tests/ElasticSearch/JsonDocument/data/place/indexed.json
- Fixed permanent events without opening hours ("infinite events" / "always open") from being filtered out when searching by `dateRange` in the `q` parameter, or when searching with the `dateFrom` and `dateTo` parameters. And same fix for `localTimeRange`.
---
Ticket: https://jira.uitdatabank.be/browse/III-4385
=> III-4385 Fix permanent events without opening hours being filtered out when searching by dateRange / dateFrom / dateTo

app/Organizer/OrganizerSearchServiceProvider.php, src/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilder.php, src/Http/OrganizerSearchController.php, src/Http/Parameters/OrganizerSupportedParameters.php, src/Organizer/OrganizerQueryBuilderInterface.php, tests/ElasticSearch/Offer/ElasticSearchOfferSearchServiceTest.php, tests/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilderTest.php, tests/ElasticSearch/Organizer/ElasticSearchOrganizerSearchServiceTest.php, tests/Http/MockOrganizerQueryBuilder.php, tests/Http/OrganizerSearchControllerTest.php
- Added `withRegionFilter` implementation inside `ElasticSearchOrganizerQueryBuilder`
- Added `withRegionFilter` call inside `OrganizerSearchController`
- Added `regions` as supported parameter
- Added `region` facet support
---
Ticket: https://jira.uitdatabank.be/browse/III-4424
=> III-4424 Implement searching on regions for Organizers

src/ElasticSearch/AbstractElasticSearchQueryBuilder.php, tests/ElasticSearch/Offer/ElasticSearchOfferQueryBuilderTest.php
- Added check that `start` + `limit` are not more than 10000 together. I added it to the Elasticsearch implementation of the query builder and not the VOs because this constraint is specific to Elasticsearch, not our own limits.
---
Ticket: https://jira.uitdatabank.be/browse/III-3923
=> III-3923 Add check that start + limit are not more than 10000 together

app/Error/ApiExceptionHandler.php, app/Error/ApiProblemFactory.php, app/Error/ErrorLoggerHandler.php
- Updated the API error handler to return a better API problem for invalid q parameters (see ticket description)
- Changed the logger error handler to only log errors that have a status code >= 500 (when converted to API problem) (we cannot do this approach in udb3-silex right now because we still have a lot of endpoints that throw exceptions that get converted to 400 but should still be logged because it's unclear if it's a bug or a bad request due to generic exception types)
---
Ticket: https://jira.uitdatabank.be/browse/III-4582
=> III-4582 API problem for invalid `q` parameter

app/RoutingServiceProvider.php, src/Http/Authentication/AuthenticateRequest.php, src/Http/Authentication/Consumer.php, src/Http/DefaultQuery/DefaultQueryConfigRepository.php, src/Http/DefaultQuery/DefaultQueryRepository.php, src/Http/DefaultQuery/InMemoryDefaultQueryRepository.php, tests/Http/Authentication/AuthenticateRequestTest.php
- Load default queries from a simple config file containing an associative array. If the config does not contain an entry for the given API key a fallback is done to check UiTID
---
Ticket: https://jira.uitdatabank.be/browse/III-4834
=> III-4834 Load default query from simple array config

.github/CODEOWNERS
- Made @willaerk and @paulherbosch codeowner of Jenkins-related files so they get assigned as reviewer by dependabot if it detects security issues in the gems and/or we make changes to the deployment code
=> Make Kristof and Paul owners of Jenkins-related files

lib/tasks/build_artifact.rake
- Basedir is now /var/www/udb3-search-service
---
Ticket: https://jira.uitdatabank.be/browse/III-4993
=> Use /var/www/udb3-search-service as basedir for deployment

src/ElasticSearch/Offer/ElasticSearchOfferQueryBuilder.php, tests/ElasticSearch/Offer/ElasticSearchOfferQueryBuilderTest.php
- Fixed the `uitpas=true` filter by filtering on the event's UiTPAS labels instead of the organizer's UiTPAS labels
---
Ticket: https://jira.uitdatabank.be/browse/III-5053
=> III-5053 Fix `uitpas=true` filter

composer.lock
- Updated calendar-summary to v4.0.1
---
Ticket: https://jira.uitdatabank.be/browse/III-5110
=> III-5110 Update Calendar Summary to v.4.0.1

readme.md
- Use correct path in `README.md` for `*SupportedParameters.php`-files
=> Use correct path for *SupportedParameters.php files

src/JsonDocument/GuzzleJsonDocumentFetcher.php, tests/JsonDocument/JsonDocumentFetcherTest.php
- `GuzzleJsonDocumentFetcher` store `Auth0Token` and only renew it after a `401`-Request
- `JsonDocumentFetcherTest` added test to check if tokens are refreshed
- `JsonDocumentFetcherTest` added test to check that tokens are not infinitely refreshed
---
Ticket: https://jira.uitdatabank.be/browse/III-5326
=> III-5326 refactor guzzle json document fetcher

app/RoutingServiceProvider.php, src/Http/Authentication/Auth0Client.php, tests/Http/Authentication/Auth0TokenProviderTest.php, tests/Http/Authentication/AuthenticateRequestTest.php, tests/JsonDocument/JsonDocumentFetcherTest.php
- Make `$audience` mandatory instead of optional in `Auth0Client`
---
Ticket: https://jira.uitdatabank.be/browse/III-5326
=> III-5326 Make $audience mandatory

docker.md
- Used custom RabbitMQ image with preconfigured exchange and queues equal to Vagrant setup
=> Use custom RabbitMQP setup

app/Organizer/OrganizerSearchServiceProvider.php, src/ElasticSearch/Operations/SchemaVersions.php, src/ElasticSearch/Operations/json/mapping_organizer.json, src/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilder.php, src/Http/Organizer/RequestParser/IdRequestParser.php, src/Http/Parameters/OrganizerSupportedParameters.php, src/Organizer/OrganizerQueryBuilderInterface.php, tests/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilderTest.php, tests/Http/MockOrganizerQueryBuilder.php, tests/Http/Organizer/RequestParser/IdRequestParserTest.php
- Added `id` to the mapping for `Organizers`
- Added `id` to `OrganizerSupportedParameters`
- `IdRequestParser` for `Organizers`
- Updated the `UDB3_CORE` version number
- `id` is now valid parameter for `Organizers`
- `OrganizerSearchServiceProvider`: injection of `IdRequestParser`
---
Ticket: https://jira.uitdatabank.be/browse/III-4590
=> III-4590 Organizers id filter

src/ElasticSearch/JsonDocument/OrganizerTransformer.php, src/ElasticSearch/Operations/SchemaVersions.php, src/ElasticSearch/Operations/json/mapping_organizer.json, src/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilder.php, src/ElasticSearch/Organizer/OrganizerPredefinedQueryStringFields.php, tests/ElasticSearch/JsonDocument/OrganizerTransformerTest.php, tests/ElasticSearch/JsonDocument/data/organizer/indexed-with-description.json, tests/ElasticSearch/JsonDocument/data/organizer/original-with-description.json, tests/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilderTest.php, tests/ElasticSearch/Organizer/OrganizerPredefinedQueryStringFieldsTest.php
- `OrganizerPredefinedQueryStringFields` to get set of predefined fields for `Organizer` & `UnitTest`
- Testfiles for `Organizer` with `description`
- Added `DescriptionTransformer` in `OrganizerTransformer`
- Added `description` to `mapping_organizer.json`
- Added `OrganizerPredefinedQueryStringFields` to `ElasticSearchOrganizerQueryBuilder`
- Updated `UDB3_CORE` Version
- Updated `UnitTests` of `ElasticSearchOrganizerQueryBuilder` after inclusion of `PredefinedQueryStringFields`
- `UnitTest` for indexation in `OrganizerTransformerTest` for `Organizers` with `description`
---
Ticket: https://jira.uitdatabank.be/browse/III-5315
=> III-5315 q=* behaviour on Organizer

src/ElasticSearch/Operations/SchemaVersions.php
- Updated `GEOSHAPES` version for Zwijndrecht.
---
Ticket: https://jira.uitdatabank.be/browse/III-5836
=> III-5836: Updated GeoShapes version for Zwijndrecht

app/RoutingServiceProvider.php
- [Allow 'x-client-properties' header](https://github.com/cultuurnet/udb3-search-service/pull/257/commits/cdbd3b97fd902d6c3178bf52cadffc1417194a61)
For more context see:
https://jira.publiq.be/browse/III-4140
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4696
=> UPS-4696 - Allow 'x-client-properties' header

app/JsonDocumentFetcherProvider.php
- Return HTTP errors instead of throwing them as exceptions by setting `http_errors` to `false`
---
Ticket: https://jira.uitdatabank.be/browse/III-5973
=> III-5973 Return HTTP errors instead of throwing

composer.lock
- Updated library `calendar-summary-v3` to latest release
---
Ticket: https://jira.publiq.be/browse/III-5869
=> III-5869: update calendar-summary-v3

rector.php, src/Http/Offer/RequestParser/SortByOfferRequestParser.php, src/Http/Organizer/RequestParser/SortByOrganizerRequestParser.php
Changed long form closures to short handed arrow functions, but formatted the code to be on 2 lines.
=> Revert back to short arrow functions

composer.json, composer.lock
- `composer.json`: Updated `calendar-summary-v3` to `4.0.7`
---
Ticket: https://jira.publiq.be/browse/III-6186
=> III-6186: update calsum to 4.0.7

app/RoutingServiceProvider.php, src/Http/Authentication/Auth0/Auth0MetadataGenerator.php, src/Http/Authentication/AuthenticateRequest.php, src/Http/Authentication/MetadataGenerator.php, tests/Http/Authentication/AuthenticateRequestTest.php
- Refactor code to use generic `MetadataGenerator` instead of `Auth0Client`
---
Ticket: https://jira.uitdatabank.be/browse/III-6220
=> III-6220 Refactor code to use generic `MetadataGenerator`

src/Http/Authentication/Keycloak/KeycloakTokenGenerator.php
- On ACC Keycloak a content header is required for the login endpoint
---
Ticket: https://jira.uitdatabank.be/browse/III-6220
=> III-6220 On ACC a content header is required for the login endpoint

composer.json, composer.lock
`Composer.json`: updated `calendar-summary-v3` to `4.0.8` 
---
Ticket: https://jira.uitdatabank.be/browse/III-6186
=> III-6186 update calsum to 4.0.8

src/Http/Authentication/AuthenticateRequest.php, src/Http/Authentication/JsonWebToken.php, tests/Http/Authentication/AuthenticateRequestTest.php
- Check issuer for JWT when working with Keycloak to determine if a token is a JWT issued token
- Requires config change https://github.com/cultuurnet/appconfig/pull/694
---
Ticket: https://jira.uitdatabank.be/browse/III-6220
=> III-6220 Check issuer for JWT when working with Keycloak

phpstan.neon, src/ElasticSearch/Aggregation/Bucket.php, src/Http/Organizer/RequestParser/CompositeOrganizerRequestParser.php, src/PagedResultSet.php, tests/ElasticSearch/Aggregation/BucketTest.php
- Increased PHPStan to level 5
---
Ticket: https://jira.uitdatabank.be/browse/III-3558
=> III-3558 Increase PHPStan to level 5

app/BaseServiceProvider.php, app/Console/AbstractMappingCommand.php, app/Console/AbstractReindexCommand.php, phpstan.neon, src/Deserializer/DeserializerInterface.php, src/ElasticSearch/AbstractElasticSearchQueryBuilder.php, src/ElasticSearch/IndexationStrategy/IndexationStrategy.php, src/ElasticSearch/Operations/AbstractReindexUDB3CoreOperation.php, src/ElasticSearch/Validation/ElasticSearchResponseValidatorInterface.php, src/Http/ApiRequestInterface.php, src/Http/Authentication/Auth0/Auth0MetadataGenerator.php, src/Http/Authentication/Keycloak/KeycloakMetadataGenerator.php, src/Http/Authentication/MetadataGenerator.php, src/Http/Parameters/ArrayParameterBagAdapter.php, src/Http/ResponseFactory.php, src/Json.php, src/ReadModel/DocumentGone.php, src/ReadModel/JsonDocument.php, tests/ElasticSearch/Operations/AbstractOperationTestCase.php, tests/Http/OfferSearchControllerTest.php, tests/Http/Parameters/ArrayParameterBagAdapterTest.php
- Increased PHPStan to level 6
---
Ticket: https://jira.uitdatabank.be/browse/III-3558
=> III-3558 Increase PHPStan to level 6

docker/config.sh
- Handle the moved config files to `uitdatabank` folder
- Related pull request https://github.com/cultuurnet/appconfig/pull/776
---
Ticket: https://jira.uitdatabank.be/browse/III-4932
=> III-4932 Handle the moved config files

src/Http/Authentication/AuthenticateRequest.php, src/Http/DefaultQuery/DefaultQueryRepository.php, src/Http/DefaultQuery/InMemoryDefaultQueryRepository.php, tests/Http/Authentication/AuthenticateRequestTest.php
- `DefaultQueryRepository` & `InMemoryDefaultQueryRepository`: added `getByClientId()`
- `AuthenticateRequest`: Check if there is a `defaultQuery` when using a `clientId`
- `AuthenticateRequestTest`: Updated test for `defaultQuery` when using an `apiKey` & added a test for a `defaultQuery` when using a `clientId`.
- We can now use default queries when using a `clientId`
- https://github.com/cultuurnet/udb3-backend/pull/1956 (Acceptance test)
- https://github.com/cultuurnet/appconfig/pull/924 (Config)
---
Ticket: https://jira.publiq.be/browse/III-6465
=> III-6465 client id filter

.github/workflows/ci.yml, composer.json, composer.lock
- Added unused packages detector package
---
Only `php-http/guzzle7-adapter` is unused, unfortunately removing it is impossible because the `php-http/discovery` plugin automatically adds it back to ensure we have a valid PSR implementation. But since Guzzle does already come with one, I'm guessing this should not trigger? Or were we making Guzzle interact with a non PSR18 library somewhere, I didn't see that in the Guzzle parts but maybe I missed it 🤔 If not I can perhaps turn off the plugin discovery
Ticket: https://jira.publiq.be/browse/III-3818
=> Added unused packages detector package

src/FileReader.php
When trying to read a file that does not exist, we get the error "Invalid HTTP status code.".
For the outside world this just looks like a status code 500, without a body.
To improve this error and make it more clear what is happening, I handled the file_get_contents more elegant.
We now get this error:
{
"title": "Internal Server Error",
"type": "about:blank",
"status": 500,
"detail": "Failed to read file file:///var/www/html/app/../public-keycloak.pem"
}
If prefered I can also remove the file name from the detail.
---
Ticket: https://jira.uitdatabank.be/browse/III-6234 
Sentry ticket: https://publiq-vzw.sentry.io/issues/4727822430/?project=5439598&referrer=jira_integration
=> III-6234 Improve error handeling when file does not exist to read

app/RoutingServiceProvider.php, src/Http/Authentication/Access/CachedClientIdResolver.php, src/Http/Authentication/Access/CachedConsumerResolver.php, tests/Http/Authentication/Access/CachedClientIdResolverTest.php, tests/Http/Authentication/Access/CachedConsumerResolverTest.php
- `CachedConsumerResolver`: `ConsumerResolver` with caching
- `CachedConsumerResolverTest`: Unit tests for `CachedConsumerResolver`
- `RoutingServiceProvider`: Use `CachedConsumerResolver` instead of `CulturefeedConsumerResolver` if toggle is enabled
- `CachedClientIdResolver`: Use suffixes for clarity
- `CachedClientIdResolverTest`: Use suffixes for clarity + refactored unnecessary code in existing unit test.
---
Ticket: https://jira.publiq.be/browse/III-6472
=> III-6472 Add CachedConsumerProvider

.github/workflows/ci.yml
- `ci.yml`: Updated github ci cache from v2 to v3
- See: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
---
Ticket: https://jira.publiq.be/browse/III-6522
=> III-6522 update cache to v3

src/Http/Authentication/Access/CultureFeedConsumerResolver.php, src/Http/Authentication/Access/InvalidConsumer.php, src/Http/Authentication/AuthenticateRequest.php, tests/Http/Authentication/Access/CultureFeedConsumerResolverTest.php, tests/Http/Authentication/AuthenticateRequestTest.php
- `InvalidConsumer`: new Exception to use instead of a pseudo-status
- `CultureFeedConsumerResolver`: Don't log Invalid Request for Consumer+throw Exception instead of creating a pseudo-status.
- `AuthenticateRequest`: Catch new Exception instead of pseudo-status
- `CultureFeedConsumerResolverTest` & `AuthenticateRequestTest`: Updated unit tests.
- Less pollution in Sentry.
---
Ticket: https://jira.publiq.be/browse/III-6521
=> III-6521 remove unneeded logging

.github/workflows/acceptance_tests.yml
**We need the buildWithParameters endpoint as the job accepts parameters**
=> We need the buildWithParameters endpoint as the job accepts parameters
