cultuurnet/udb3-search-service

app/Organizer/OrganizerControllerProvider.php
src/ElasticSearch/Event/EventJsonDocumentTransformer.php
src/ElasticSearch/JsonDocument/CopyJson/CopyJsonCreatedModified.php
src/ElasticSearch/JsonDocument/CopyJson/CopyJsonOffer.php
src/ElasticSearch/JsonDocument/CopyJson/Logging/CopyJsonLoggerInterface.php
src/ElasticSearch/JsonDocument/CopyJson/Logging/CopyJsonPsrLogger.php
src/ElasticSearch/Offer/AbstractOfferJsonDocumentTransformer.php
src/ElasticSearch/Operations/SchemaVersions.php
src/ElasticSearch/Operations/json/mapping_organizer.json
src/ElasticSearch/Organizer/CopyJsonOrganizer.php
src/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilder.php
src/ElasticSearch/Place/PlaceJsonDocumentTransformer.php
src/Http/Organizer/RequestParser/SortByOrganizerRequestParser.php
src/Http/Parameters/OrganizerParameterWhiteList.php
src/Organizer/OrganizerQueryBuilderInterface.php
tests/ElasticSearch/Event/EventJsonDocumentTransformerTest.php
tests/ElasticSearch/Organizer/data/all_languages_indexed.json
tests/ElasticSearch/Organizer/data/indexed.json
tests/ElasticSearch/Organizer/data/indexed_with_name_as_string.json
tests/ElasticSearch/Organizer/data/indexed_with_translated_address.json
tests/ElasticSearch/Organizer/data/indexed_with_workflowstatus_deleted.json
tests/ElasticSearch/Organizer/data/missing_main_language_indexed.json
tests/ElasticSearch/Place/PlaceJsonDocumentTransformerTest.php
tests/Http/MockOrganizerQueryBuilder.php
tests/Http/OrganizerSearchControllerTest.php

- Organizers can now be sorted by either score, created or modified.
---
Ticket: https://jira.uitdatabank.be/browse/III-3067

Add sort parameter to organizers

---

composer.json
composer.lock

- Fixed fatal error on environments that use API keys

Add cultuurnet/auth dependency

---

app/Offer/OfferControllerProvider.php
src/Organizer/OrganizerJsonDocumentLanguageAnalyzer.php

- Fixed an undefined service in the service container. This causes the application to crash so should be reviewed asap (but this bug hasn't been deployed yet afaik)
- Fixed coding standards

Fix undefined service

---

composer.json
composer.lock

- bump cultuurnet/udb3-api-guard dependency
---
Ticket:
[jira](https://jira.uitdatabank.be/browse/III-3004)

Feature III-3004

---

app/ApiKey/ApiGuardServiceProvider.php
app/BaseServiceProvider.php

- Fixed consumers' default queries not working

Fix default query not working for consumers

---

app/Organizer/OrganizerServiceProvider.php
src/ElasticSearch/AbstractElasticSearchQueryBuilder.php
src/ElasticSearch/HasElasticSearchClient.php
src/ElasticSearch/Offer/ElasticSearchOfferSearchService.php
src/ElasticSearch/Organizer/ElasticSearchOrganizerSearchService.php
src/Http/OfferSearchController.php
src/Http/OrganizerSearchController.php
tests/Http/OrganizerSearchControllerTest.php

- Added a shard preference based on the api key so requests coming from the same consumer use a consistent shard ordering
---
Ticket: https://jira.uitdatabank.be/browse/III-3153

Add shard preference

---

.github/workflows/ci.yml

- Updated Github actions config to run the jobs for every branch / PR, not just those pointing to master

Run github actions on every branch / PR

---

app/Error/SentryExceptionHandler.php
app/Factory/ContainerFactory.php
app/Factory/ErrorHandlerFactory.php
app/SentryServiceProvider.php
bin/app.php
composer.json
composer.lock
config.dist.yml
web/index.php

- Added Sentry integration
---
https://jira.uitdatabank.be/browse/III-3386

III-3386 Integrate Sentry SDK

---

app/Error/ApiExceptionHandler.php

- Avoid reporting instances of type error to fix potential security issue that could expose sensitive data.
---
Ticket: https://jira.uitdatabank.be/browse/III-3386

III-3386 Avoid reporting instances of type error

---

app/Error/SentryExceptionHandler.php
app/Factory/ErrorHandlerFactory.php
web/index.php

- Add api key and runtime environment
---
Ticket: https://jira.uitdatabank.be/browse/III-3528

III-3528 Capture user info

---

src/ElasticSearch/Operations/SchemaVersions.php

- Update UDB3 core schema version to force reindex
---
Ticket: https://jira.uitdatabank.be/browse/III-3476

III-3476 Update UDB3 core schema version to force reindex

---

app/AmqpProvider.php
app/Console/ConsumeCommand.php
app/Error/SentryPsrLoggerDecorator.php
composer.json
composer.lock
src/AMQP/AbstractConsumer.php
src/AMQP/ConsumerInterface.php
src/AMQP/DomainMessageJSONDeserializer.php
src/AMQP/EventBusForwardingConsumer.php
src/AMQP/EventBusForwardingConsumerFactory.php
tests/AMQP/DomainMessageJSONDeserializerTest.php
tests/AMQP/Dummies/DummyEvent.php
tests/AMQP/Dummies/DummyEventNotSerializable.php
tests/AMQP/Dummies/domain-message-dummy-event.json
tests/AMQP/EventBusForwardingConsumerTest.php

- Internalize Broadway AMQP
---
Ticket: https://jira.uitdatabank.be/browse/III-3719

III-3719 Internalize Broadway AMQP

---

app/ApiKey/ApiGuardServiceProvider.php
composer.json
composer.lock

- Removed unnecessary usage of `CultuurNet\Auth\ConsumerCredentials`
- Removed `cultuurnet/auth` dependency

Remove cultuurnet/auth dependency

---

.github/workflows/ci.yml

- Remove PHP extensions from GitHub actions

Remove PHP extensions from GitHub actions

---

src/Http/Parameters/OfferSupportedParameters.php

- Fixed unknown parameter `embedCalendarSummaries`
---
Ticket: https://jira.uitdatabank.be/browse/III-3829

Add embedCalendarSummaries to list of valid parameters

---

app/AmqpProvider.php
src/AMQP/Delay.php
src/AMQP/EventBusForwardingConsumerFactory.php
src/ElasticSearch/AbstractElasticSearchQueryBuilder.php
src/ElasticSearch/Offer/ElasticSearchOfferQueryBuilder.php
src/Http/Offer/RequestParser/AgeRangeOfferRequestParser.php
src/Natural.php
src/Offer/Age.php
src/Offer/OfferQueryBuilderInterface.php
src/PriceInfo/Price.php
tests/ElasticSearch/Offer/ElasticSearchOfferQueryBuilderTest.php
tests/Http/MockOfferQueryBuilder.php
tests/Http/Offer/RequestParser/AgeRangeOfferRequestParserTest.php
tests/Http/OfferSearchControllerTest.php
tests/NaturalTest.php
tests/PriceInfo/PriceTest.php

- Added custom abstract `Natural` class
- Added custom `Delay` class
- Added custom `Age` class
- Refactor `Price` class to use custom abstract `Natural` class
---
Ticket: https://jira.uitdatabank.be/browse/III-3851

III-3851 Refactor Natural value object

---

src/ElasticSearch/JsonDocument/Properties/Url.php
src/ElasticSearch/JsonDocument/Properties/UrlTransformer.php
src/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilder.php
src/Http/OrganizerSearchController.php
src/Organizer/OrganizerQueryBuilderInterface.php
src/PriceInfo/Price.php
tests/ElasticSearch/JsonDocument/Properties/UrlTransformerTest.php
tests/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilderTest.php
tests/Http/MockOrganizerQueryBuilder.php
tests/Http/OrganizerSearchControllerTest.php

- Added custom `Url` implementation
---
Ticket: https://jira.uitdatabank.be/browse/III-3851

III-3851 Refactor Uri to custom Url implementation

---

.github/dependabot.yml
composer.lock
tests/AMQP/EventBusForwardingConsumerTest.php

-  Enable dependabot version updates
---
Ticket: https://jira.uitdatabank.be/browse/III-3855

III-3855 Enable dependabot version updates

---

composer.json
composer.lock

- Loosened `symfony/console` constraint

Loosen symfony/console constraint

---

composer.json
composer.lock
src/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilder.php
tests/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilderTest.php

Remove stringy dependency

---

app/Error/ErrorLoggerHandler.php

- Fixed implementations/child classes of bad request exceptions being logged
---
Ticket: https://jira.uitdatabank.be/browse/III-3816

Fix implementations/child classes of bad request exceptions being logged

---

app/AmqpLoggerProvider.php
app/AmqpProvider.php
app/ElasticSearchProvider.php
app/Error/LoggerName.php
app/Event/EventIndexationServiceProvider.php
app/JsonDocumentFetcherProvider.php
app/Organizer/OrganizerIndexationServiceProvider.php
app/Place/PlaceIndexationServiceProvider.php
bin/app.php
web/index.php

- Changed `amqp.log` filename to `amqp.udb3.log`
---
Ticket: https://jira.uitdatabank.be/browse/III-3881

III-3881 Make logger filenames consistent with udb3-silex

---

src/ElasticSearch/JsonDocument/CalendarSummaryEmbeddingJsonTransformer.php
tests/ElasticSearch/JsonDocument/CalendarSummaryEmbeddingJsonTransformerTest.php

- Added multiple language support to calendar summary
---
Ticket: https://jira.uitdatabank.be/browse/III-3933

III-3933 Add multi language support to calendar summary

---

.gitignore
app/RoutingServiceProvider.php
cache/.gitignore
tests/Http/Authentication/Auth0TokenFileRepositoryTest.php

- Store the Auth0 cache file inside a cache folder
---
Ticket: https://jira.uitdatabank.be/browse/III-4116

III-4116 Store the Auth0 cache file inside a cache folder

---

app/RoutingServiceProvider.php
config.dist.yml

- `X-Client-Id` as allowed header (I tried changing it to just `*` as with the origins, but that didn't work for headers)
- Unused `cors` config parameters from example config file
---
Ticket: https://jira.uitdatabank.be/browse/III-4140

III-4140 Fix CORS requests from Stoplight not working on SAPI3

---

composer.json
composer.lock

- Updated calendar-summary-v3 to v3.3
---
Ticket: https://jira.uitdatabank.be/browse/III-4190

III-4190 Update calendar-summary-v3 to v3.3

---

composer.json
composer.lock
tests/ElasticSearch/JsonDocument/CalendarSummaryEmbeddingJsonTransformerTest.php

- Upgrade cultuurnet/calendar-summary-v3 to version 3.4

Upgrade cultuurnet/calendar-summary-v3 to version 3.4

---

src/ElasticSearch/JsonDocument/Properties/MetadataTransformer.php
src/ElasticSearch/Offer/ElasticSearchOfferQueryBuilder.php
src/ElasticSearch/Operations/SchemaVersions.php
src/ElasticSearch/Operations/json/mapping_event.json
src/Http/Offer/RequestParser/SortByOfferRequestParser.php
src/Http/OfferSearchController.php
src/Http/Parameters/OfferSupportedParameters.php
src/Offer/OfferQueryBuilderInterface.php
tests/ElasticSearch/JsonDocument/data/event/indexed-with-metadata.json
tests/ElasticSearch/JsonDocument/data/event/original-with-metadata.json
tests/ElasticSearch/Offer/ElasticSearchOfferQueryBuilderTest.php
tests/Http/MockOfferQueryBuilder.php
tests/Http/OfferSearchControllerTest.php

- Added mapping on event for recommendationFor 
- Added transformation for recommendationFor
- Added query parameter for recommendationFor
- Added sort parameter for recommendationScore
- Incremented UDB3_CORE schema version
---
Ticket: https://jira.uitdatabank.be/browse/III-4353

III-4353 Index recommendation for and make it also sortable

---

src/ElasticSearch/Offer/ElasticSearchOfferQueryBuilder.php
src/ElasticSearch/Operations/SchemaVersions.php
src/ElasticSearch/Operations/json/mapping_event.json
src/Http/Offer/RequestParser/SortByOfferRequestParser.php
src/Http/OfferSearchController.php
src/Offer/OfferQueryBuilderInterface.php
tests/ElasticSearch/Offer/ElasticSearchOfferQueryBuilderTest.php
tests/Http/MockOfferQueryBuilder.php
tests/Http/OfferSearchControllerTest.php

- Fixed recommendation sorting by using nested type
---
Ticket: https://jira.uitdatabank.be/browse/III-4386

III-4386 Fix recommendation sorting

---

app/ElasticSearchProvider.php
app/Offer/OfferSearchControllerFactory.php
app/Organizer/OrganizerSearchServiceProvider.php
tests/Http/Offer/RequestParser/GeoBoundsOfferRequestParserTest.php
tests/Http/OfferSearchControllerTest.php
tests/Http/OrganizerSearchControllerTest.php

- Improved type hinting on various classes related to organizer search
---
Ticket: https://jira.uitdatabank.be/browse/III-4424

III-4424 Boy scouting in context of organizer search

---

src/ElasticSearch/JsonDocument/JsonLdPolyfillJsonTransformer.php
tests/ElasticSearch/JsonDocument/JsonLdPolyfillJsonTransformerTest.php

- Added polyfills for mediaObject / images properties (see https://github.com/cultuurnet/udb3-silex/pull/964)
---
Ticket: https://jira.uitdatabank.be/browse/III-4503

III-4503 Add polyfills for mediaObject / images properties

---

src/ElasticSearch/JsonDocument/OrganizerTransformer.php
src/ElasticSearch/JsonDocument/Properties/ImagesTransformer.php
src/ElasticSearch/Operations/SchemaVersions.php
src/ElasticSearch/Operations/json/mapping_organizer.json
src/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilder.php
src/Http/OrganizerSearchController.php
src/Http/Parameters/OrganizerSupportedParameters.php
src/Organizer/OrganizerQueryBuilderInterface.php
tests/ElasticSearch/JsonDocument/OrganizerTransformerTest.php
tests/ElasticSearch/JsonDocument/data/organizer/all_languages_indexed.json
tests/ElasticSearch/JsonDocument/data/organizer/indexed.json
tests/ElasticSearch/JsonDocument/data/organizer/indexed_with_images.json
tests/ElasticSearch/JsonDocument/data/organizer/indexed_with_regions.json
tests/ElasticSearch/JsonDocument/data/organizer/indexed_with_translated_address.json
tests/ElasticSearch/JsonDocument/data/organizer/indexed_with_workflowstatus_deleted.json
tests/ElasticSearch/JsonDocument/data/organizer/missing_main_language_indexed.json
tests/ElasticSearch/JsonDocument/data/organizer/original_with_images.json
tests/Http/MockOrganizerQueryBuilder.php
tests/Http/OrganizerSearchControllerTest.php

- Index the `imagesCount` of an Organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-4680

III-4680 Index the organizer images count

---

.github/CODEOWNERS

- Added CODEOWNERS file for automatic reviewer assignments

Add CODEOWNERS file for automatic reviewer assignments

---

composer.json
composer.lock
src/AMQP/DomainMessageJSONDeserializer.php
src/AbstractSearchProjector.php
src/Event/EventProjectedToJSONLD.php
src/Organizer/OrganizerProjectedToJSONLD.php
src/Place/PlaceProjectedToJSONLD.php
src/SimpleEventBus.php
tests/AMQP/Dummies/DummyEvent.php

- Updated `broadway/broadway` from `1.0.0` to `2.4.0` and fixed breaking changes
---
Ticket: https://jira.uitdatabank.be/browse/III-4805

III-4805 Broadway update

---

src/ElasticSearch/JsonDocument/UiTPASPricesTransformer.php
src/Http/OfferSearchController.php
src/Http/OrganizerSearchController.php
src/Http/Parameters/OfferSupportedParameters.php
src/Http/ResultTransformerFactory.php
src/JsonDocument/GuzzleJsonDocumentFetcher.php
tests/ElasticSearch/JsonDocument/UiTPASPricesTransformerTest.php
tests/JsonDocument/JsonDocumentFetcherTest.php

- Created an UiTPASPricesTransformer
- Added a parameter to embed UiTPAS Prices
- Added tests for UiTPASPricesTransformer 
---
Ticket: https://jira.uitdatabank.be/browse/III-4814

III-4814 embed UiTPASPrices

---

app/AmqpProvider.php
app/CommandServiceProvider.php

- Added consume command for "related" queue
---
Ticket: https://jira.uitdatabank.be/browse/III-4822

III-4822 Add consume command for related messages queue

---

.gitignore

- Added `default_queries.php` to gitignore file
---
Ticket: https://jira.uitdatabank.be/browse/III-4843

III-4843 Ignore default queries config file

---

app/RoutingServiceProvider.php

- Initialize `DefaultQueryRepository`
---
Ticket: https://jira.uitdatabank.be/browse/III-4895

III-4895 Initialize DefaultQueryRepository

---

.gitignore
Gemfile
Gemfile.lock
Jenkinsfile
Rakefile
lib/tasks/build.rake
lib/tasks/build_artifact.rake

- Jenkinsfile for job configuration
- Rake tasks for building artifacts
---
Ticket: https://jira.uitdatabank.be/browse/III-4993

Build configuration for new Jenkins for UiTdatabank search service

---

Jenkinsfile

- Use correct environment to publish aptly snapshot to
---
Ticket: https://jira.uitdatabank.be/browse/III-4993

Use correct environment to publish to

---

composer.json
composer.lock
tests/ElasticSearch/JsonDocument/CalendarSummaryEmbeddingJsonTransformerTest.php

- Upgraded to calendar summary 4.0
---
Ticket: https://jira.uitdatabank.be/browse/III-5107

III-5107 Upgrade to calendar summary 4.0

---

composer.lock
tests/ElasticSearch/JsonDocument/CalendarSummaryEmbeddingJsonTransformerTest.php

- Update Calendar Summary to 4.0.2
- Fixed tests after calsum update
---
Ticket: https://jira.uitdatabank.be/browse/III-5136

III-5136 update calsum 4.0.2

---

docker-compose.yml

- Added hostname property to avoid random node names (in combination with new ES image with correct owner of the data folder)
---
Ticket: https://jira.uitdatabank.be/browse/III-5414

III-5414 Add hostname property to avoid random node names

---

docker-compose.yml
docker/php/Dockerfile
docker/php/supervisord.conf

- Use Apache container instead of built-in web server
- Use supervisor to manage workers

Improve search docker setup

---

src/ElasticSearch/JsonDocument/Properties/UniqueAddressTransformer.php
tests/ElasticSearch/JsonDocument/Properties/UniqueAddressTransformerTest.php
tests/ElasticSearch/JsonDocument/data/place/indexed-duplicate.json
tests/ElasticSearch/JsonDocument/data/place/indexed-for-all-ages.json
tests/ElasticSearch/JsonDocument/data/place/indexed-modified.json
tests/ElasticSearch/JsonDocument/data/place/indexed-with-contributors.json
tests/ElasticSearch/JsonDocument/data/place/indexed-with-end-date-as-available-to.json
tests/ElasticSearch/JsonDocument/data/place/indexed-with-metadata.json
tests/ElasticSearch/JsonDocument/data/place/indexed-with-opening-hours.json
tests/ElasticSearch/JsonDocument/data/place/indexed-with-optional-fields.json
tests/ElasticSearch/JsonDocument/data/place/indexed-with-period-and-opening-hours.json
tests/ElasticSearch/JsonDocument/data/place/indexed-with-period.json
tests/ElasticSearch/JsonDocument/data/place/indexed-with-regions.json
tests/ElasticSearch/JsonDocument/data/place/indexed-without-available-from.json
tests/ElasticSearch/JsonDocument/data/place/indexed.json

- Replaced spaces with underscores in unique address identifier
---
Ticket: https://jira.uitdatabank.be/browse/III-4601

III-4601 Replace spaces with underscores in unique address identifier

---

src/ElasticSearch/Operations/SchemaVersions.php
src/ElasticSearch/Operations/json/mapping_place.json

Change identifier type to string to prevent problems with special chars like @
---
Ticket: https://jira.uitdatabank.be/browse/III-4601

III-4601 Change identifier type to string to prevent problems with special chars

---

src/ElasticSearch/JsonDocument/OrganizerTransformer.php
src/ElasticSearch/JsonDocument/Properties/EducationalDescriptionTransformer.php
src/ElasticSearch/Operations/SchemaVersions.php
src/ElasticSearch/Operations/json/mapping_organizer.json
tests/ElasticSearch/JsonDocument/OrganizerTransformerTest.php
tests/ElasticSearch/JsonDocument/data/organizer/indexed-with-educational-description.json
tests/ElasticSearch/JsonDocument/data/organizer/original-with-educational-description.json

- Indexed educational description but only exposed it for advanced queries and not as a URL parameter.
---
Ticket: https://jira.uitdatabank.be/browse/III-5855

III-5855 Index educational description

---

bin/app.php

- Avoid catching exceptions in CLI to make them flow to Sentry
---
Ticket: https://jira.uitdatabank.be/browse/III-5998

III-5998 Avoid catching exceptions in CLI to make them flow to Sentry

---

.github/CODEOWNERS

Add Koen as code owner

---

src/ElasticSearch/Offer/ElasticSearchOfferQueryBuilder.php
src/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilder.php
src/Http/Offer/RequestParser/SortByOfferRequestParser.php
src/Http/Organizer/RequestParser/SortByOrganizerRequestParser.php
src/Offer/OfferQueryBuilderInterface.php
src/Organizer/OrganizerQueryBuilderInterface.php
tests/Http/MockOfferQueryBuilder.php
tests/Http/MockOrganizerQueryBuilder.php
tests/Http/OfferSearchControllerTest.php
tests/Http/OrganizerSearchControllerTest.php

- Added completeness as sort option for organizers and offers
---
Ticket: https://jira.uitdatabank.be/browse/III-6036

III-6036 Add completeness as sort option

---

Makefile
app/Error/ApiExceptionHandler.php
app/Factory/ErrorHandlerFactory.php
composer.json
composer.lock
web/index.php

- Remove zendframework/zend-httphandlerrunner for Laminas replacement
---
Ticket: https://jira.uitdatabank.be/browse/III-III-6128

III-6128 Remove zendframework/zend-httphandlerrunner

---

composer.json
composer.lock

Upgrade slim-psr7 to 1.6
---
Ticket: https://jira.uitdatabank.be/browse/III-6128

III-6128 Upgrade slim-psr7 to 1.6

---

.github/workflows/ci.yml
src/Http/Parameters/ArrayParameterBagAdapter.php

Add PHP 8.0 to workflow CLI steps
If I did everything right, this should be proof sapi3 is ready for PHP8!
---
Ticket: https://jira.uitdatabank.be/browse/III-6128

III-6128 Add PHP 8.0 to workflow CLI steps

---

composer.json
composer.lock

Upgrade "cultuurnet/culturefeed-php" to "1.14"
---
Ticket: https://jira.uitdatabank.be/browse/III-6128

III-6128 Upgrade "cultuurnet/culturefeed-php" to "1.14"

---

docker.md
docker/config.sh

- `config.sh`:  Add `host.docker.internal` via `make config`
- `docker.md`: update info about `host.docker.internal`
---
Ticket: https://jira.publiq.be/browse/III-6155

III-6155 update /etc/hosts via config

---

lib/tasks/build.rake
lib/tasks/build_artifact.rake
lib/tasks/clean.rake

Ticket: https://jira.uitdatabank.be/browse/III-6160

Add features.yml as config file to artifact

---

Makefile
docker/config.sh

- Copied pem files from common key location
---
Ticket: https://jira.uitdatabank.be/browse/III-6216

III-6216 Copy pem files from common key location

---

app/RoutingServiceProvider.php

- Read pem file based on config, being Keycloak enabled or not
---
Ticket: https://jira.uitdatabank.be/browse/III-6216

III-6216 Read pem file based on config

---

Jenkinsfile

---
Ticket: https://jira.uitdatabank.be/browse/III-6188

Publish artifacts to focal to allow deploying new servers

---

lib/tasks/build_artifact.rake

---
Ticket: https://jira.uitdatabank.be/browse/III-6188

Do not package the tests and docker related files

---

Jenkinsfile

---
Ticket: https://jira.uitdatabank.be/browse/III-6197

Build on Ubuntu 20.04 from now on, and deploy to the new servers

---

Jenkinsfile

---
Ticket: https://jira.uitdatabank.be/browse/III-6197

Force deploying on Jenkins agent in new VPC to allow DNS resolution

---

app/BaseServiceProvider.php
app/Console/TermTaxonomyToFacetMappingsCommand.php
app/RoutingServiceProvider.php
phpstan.neon
src/AMQP/DomainMessageJSONDeserializer.php
src/AbstractSearchProjector.php
src/ElasticSearch/AbstractElasticSearchQueryBuilder.php
src/ElasticSearch/ElasticSearchPagedResultSetFactory.php
src/ElasticSearch/JsonDocument/Properties/Url.php
src/ElasticSearch/Offer/ElasticSearchOfferQueryBuilder.php
src/ElasticSearch/Organizer/ElasticSearchOrganizerQueryBuilder.php
src/Http/Authentication/JsonWebToken.php
src/Http/Parameters/ArrayParameterBagAdapter.php
src/Json.php
src/Language/MultilingualString.php
tests/Http/Authentication/JsonWebTokenFactory.php
tests/Http/MockOfferQueryBuilder.php
tests/Http/MockOrganizerQueryBuilder.php
tests/PagedResultSetTest.php

- Improved various type hints in comments
- Improved several inline type hints
- Handle return types of internal PHP methods better
---
Ticket: https://jira.uitdatabank.be/browse/III-3558

III-3558 Improve type hinting to reach PHPStan level 7

---

app/RoutingServiceProvider.php
phpstan.neon

- Hotfix for missing default queries

Hotfix for missing default queries

---

.github/workflows/ci.yml
composer.json
composer.lock
docker/php/Dockerfile

- Added PHP 8.1 to CI matrix
- Upgraded packages packages are `cakephp/chronos`, `hassankhan/config` and `php-amqplib/php-amqplib`
- Upgraded composer to 2.6.6 in PHP Docker file
---
Ticket: https://jira.uitdatabank.be/browse/III-5031

III-5031 Support PHP 8.1

---

.gitignore

- Ignore default queries correctly
- Ignore PHPUnit cache

Improve git ignore

---

docker-compose.yml

- Removed version from docker-compose yml file

Remove version from docker-compose yml file

---

app/Console/AbstractMappingCommand.php
app/Console/AbstractReindexCommand.php
app/Error/ApiExceptionHandler.php
src/ElasticSearch/Aggregation/Aggregation.php
src/ElasticSearch/ElasticSearchDistance.php
src/ElasticSearch/ElasticSearchDistanceFactory.php
src/ElasticSearch/JsonDocument/Properties/Url.php
src/ElasticSearch/Operations/AbstractReindexUDB3CoreOperation.php
src/ElasticSearch/Operations/CheckIndexExists.php
src/ElasticSearch/Operations/CreateIndex.php
src/ElasticSearch/Operations/DeleteIndex.php
src/ElasticSearch/Operations/GetIndexNamesFromAlias.php
src/ElasticSearch/Operations/UpdateIndexAlias.php
src/Http/Offer/RequestParser/CompositeOfferRequestParser.php
src/Http/Organizer/RequestParser/CompositeOrganizerRequestParser.php
src/JsonDocument/CompositeJsonTransformer.php
src/Language/MultilingualString.php
src/PagedResultSet.php
tests/AMQP/DomainMessageJSONDeserializerTest.php
tests/AMQP/Dummies/DummyEvent.php
tests/Deserializer/SimpleDeserializerLocatorTest.php
tests/ElasticSearch/Aggregation/NodeMapAggregationTransformerTest.php
tests/ElasticSearch/ElasticSearchDistanceTest.php
tests/ElasticSearch/JsonDocument/JsonLdPolyfillJsonTransformerTest.php
tests/Http/MockDistanceFactory.php

- Improved type hinting on properties
- Improved type hinting on function parameters
---
Ticket: https://jira.uitdatabank.be/browse/III-6308

III-6308 Improve type hinting

---

Makefile
docker-compose.yml
docker/config.sh

- `Makefile`: always use containerName & docker-compose
- `docker-compose`: Updated networking, added healthcheck
- `config.sh`: Add parameters for different functionality
- Run acceptance tests on both `docker` & `Jenkins`
---
Ticket: https://jira.publiq.be/browse/III-6154

III-6154 update hostnames

---

docker-compose.yml

---
Ticket: https://jira.uitdatabank.be/browse/III-6154

Add healthcheck to PHP container

---

src/Http/Authentication/AuthenticateRequest.php

- Change Auth0 down to generic message about OAuth server
---
Ticket: https://jira.uitdatabank.be/browse/III-6156

III-6156 Change Auth0 down to generic message

---

composer.json
composer.lock

- Added `php-http/guzzle7-adapter` again

Add `php-http/guzzle7-adapter` again

---

app/Factory/ContainerFactory.php
app/RoutingServiceProvider.php

- `ContainerFactory`: Always add `CacheProvider`
- `RoutingServiceProvider`: Always use `CachedConsumerResolver` & `CachedClientIdResolver` & create inline
- https://github.com/cultuurnet/appconfig/pull/961
---
Ticket: https://jira.publiq.be/browse/III-6509

III-6509 feature Flag removal

---

.gitignore
docker-compose.yml

- PHP port can now be configured based on local dev environment.

Configure php forward port

---

composer.json
composer.lock

- Upgraded the `league/route` package as it used an unsupported feature in php8
---
Ticket: https://jira.uitdatabank.be/browse/III-6554

III-6554 Upgrade league/route package

---

src/JsonDocument/GuzzleJsonDocumentFetcher.php

- Improved message for JSON-LD error
---
Ticket: https://jira.uitdatabank.be/browse/III-6578

III-6578 Improve message for JSON-LD error

---

.github/CODEOWNERS

- `CODEOWNERS`: Offboarding Stef
---

offboarding Stef

---

.github/CODEOWNERS

- `CODEOWNERS`: Offboarding Simon
---

offboarding Simon

---

readme.md

- `readme.md`: Add info about & link to `regression tests`.
---
Ticket: https://jira.publiq.be/browse/III-6696

III-6696 Add regression test spreadsheet.

---

features.dist.yml

- `features.dist.yml`: Remove last remnant of yml config.
---

remove last remnants of yml config
